### ISSUE TITLE
Request: add flag to show/hide country text names

### ISSUE THREAD

**Issue by rjswellframe** [xtrinch/MRCountryPicker#11]

**Comment by xtrinch** [comment]
So if I understand correctly only flag images of countries and optionally phone numbers would be displayed?

**Comment by rjswellframe** [comment]
Right - this seems like one way to localize without having to translate a mountain of country names per-locale. Flag and phone prefix seems sufficient if necessary.

**Comment by xtrinch** [comment]
Actually I think this could be easily localized via built-in ios functions (Something like the following link suggests [https://stackoverflow.com/a/38635989/2402929](url)). The json provided in the assets folder has country codes included, so this shouldn't be a problem. Ofcourse strings would only be optionally localized.

Accepting pull requests if you feel up to it!

**Comment by deanrock** [comment]
@rjswellframe: I have added option to set custom locale (it defaults to system's locale if none is provided). Please check version 0.0.7.

**Comment by rjswellframe** [comment]
Great, thank you! I was planning on contributing when I had time!
