### ISSUE TITLE
Request: add new open/public method to "setCountryByNameString"

### ISSUE THREAD

**Issue by andrewmcgee** [xtrinch/MRCountryPicker#12]
I'm using this nice little picker to populate a field on one page of an app. I then read the value of the field e.g. "+1" and pass it to a 2nd page with a similar field. Ideally, I'd like to auto-populate the field on the 2nd page and set-up another picker to mirror the first page. I'm trying to do this using "setCountryByPhoneCode". However, currently if the value was +1 USA on the 1st page page, page 2 displays +1 Canada (because Canada comes before in the countries array during the loop). 

Adding a further open/public method to "setCountryByNameString" would solve this issue and be really helpful! Great little project BTW! - Thanks!

**Comment by deanrock** [comment]
@andrewmcgee I have added 'setCountryByName' method which does exactly as you asked. Please check version 0.0.7.
