### ISSUE TITLE
Unable to find a specification for pod 'MRCountryPicker', '~> 0.0.3'

### ISSUE THREAD

**Issue by nami13** [xtrinch/MRCountryPicker#2]
Hi, xtrinch
How are you?
Thanks for your country picker. It looks great.
I was trying to install your picker via Cocoapods.

I added this line to Podfile

...
pod 'MRCountryPicker', '~> 0.0.3'
...

But the installation is failed and it says "[!] Unable to find a specification for `MRCountryPicker (~> 0.0.3)`"

Please let me know how can I use your picker.

Thanks
Nami

**Comment by xtrinch** [comment]
Hi, thank you!

I've just tested it with the following podfile and it worked:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target "podstest" do
    pod 'MRCountryPicker', '~> 0.0.3'
end
```

Perhaps you should try:

> pod update

If that doesn't work:

> pod repo remove master
> pod setup
> pod install

Let me know if any of this works for you!
