### ISSUE TITLE
0.0.6 version is not downloadable via CocoaPods

### ISSUE THREAD

**Issue by theduman** [xtrinch/MRCountryPicker#7]
Hi mate. You saw the problem. If you remove the version it downloads 0.0.5 version successfully. Maybe you didnt upload the 0.0.6 version to cocoapods?

[!] Unable to satisfy the following requirements:

- `MRCountryPicker (~> 0.0.6)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `MRCountryPicker (~> 0.0.6)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by xtrinch** [comment]
Have you tried pod repo update?

**Comment by theduman** [comment]
It works now after the `pod repo update` command, you also need `sudo gem install cocoapods` after that.  A warning at README file could be helpful for others I think.

**Comment by xtrinch** [comment]
This really doesn't have much to do with this library, and the pod install command warns you that this could possibly be an issue.
